version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace/:cached
    ports: 
      - 5000:5000
      - 5001:5001
      - 8083:8083
    # プロセスが終了してコンテナが終了してしまわないように上書きする
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      ASPNETCORE_Kestrel__Endpoints__Http__Url: http://*:5001
      ASPNETCORE_ENVIRONMENT: DockerDevelopment
      ConnectionStrings__DB: Data Source=mydb,1435;Initial Catalog=owmlocal;User ID=localuser;Password=Passw0rd01!;Max Pool Size=700;trustServerCertificate=true;Trusted_Connection=False;Encrypt=False;MultipleActiveResultSets=True;ConnectRetryCount=6;ConnectRetryInterval=5;

  # SQLServer
  mydb:
    build:
        context: ../ServerApp/DB_Docker/sqlserver
        dockerfile: Dockerfile
    volumes:
      - ../ServerApp/DB_Docker/sqlserver/init-data:/init-data:delegated
    env_file:
      - ../ServerApp/DB_Docker/sqlserver/common.env
    ports:
      - 1435:1433